name: 'Run xcodebuild'
description: 'Action builds the project at the specificed project_path for workspace and scheme'

inputs:
  project_path:
    required: true
    type: string
  workspace:
    required: true
    type: string
  scheme:
    required: true
    type: string
  simulator:
    required: false
    type: string
    default: 'platform=iOS Simulator,name=iPhone 13,OS=latest'

runs:
  using: "composite"
  steps:
    - name: Build ${{ inputs.scheme }}
      run: |
        cd ${{ inputs.project_path }} 
        xcodebuild build-for-testing -workspace ${{ inputs.workspace }} -scheme ${{ inputs.scheme }} -sdk iphonesimulator -destination '${{ inputs.simulator }}' | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]} 
      shell: bash