# Blocks PRs targeting the release branch that are not created by the release GHA workflow.
name: Block Manual PR to Release

on:
  pull_request:
    branches:
      - ameter/test-release-clean  # will change to release after testing

permissions:
  pull-requests: write
  id-token: write

jobs:
  check:
    name: Block Manual PR to Release
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: true

      - name: Close PR
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.title }}
        run: |
          gh pr close $PR_NUMBER --comment "Invalid PR!\nPRs targeting the release branch must be created by the GHA release workflow."
