# Check PRs targeting the release brach to ensure they are from the release GHA workflow.

name: Check release PR

on:
  pull_request:
    branches:
      - ameter/test-release-clean  # will change to release after testing

permissions: {}

jobs:
  check:
    name: Run validation checks
    runs-on: ubuntu-latest

    steps:
      - name: Verify head ref is 'main'
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        if: ${{ env.HEAD_REF != 'main' }}
        run: |
          echo
          echo Invalid head ref!
          echo PRs targeting the release branch must have a head ref of 'main'.
          echo Current head ref: \'$GITHUB_HEAD_REF\'
          exit 1

      - name: "Verify title is 'chore: kickoff release'" 
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: "${{ env.TITLE != 'chore: kickoff release' }}"
        run: |
          echo
          echo Invalid title!
          echo PRs targeting the release branch must have the title 'chore: kickoff rlease'
          echo Current title: \'$TITLE\'
          exit 1
      
      - name: "Verify actor is '?'" 
        shell: bash
        env:
          ACTOR: ${{ github.actor }}
        if: ${{ env.ACTOR != 'blah' }} # will change to '?'
        run: |
          echo
          echo Invalid actor!
          echo PRs targeting the release branch must have the actor '?'
          echo Current actor: \'$ACTOR\'

#TODO
# change values
# add exit 1s
