# Check PRs targeting the release brach to ensure they are from the release GHA workflow.
name: Check Release PR

on:
  pull_request:
    branches:
      - ameter/test-release-clean  # will change to release after testing

permissions: {}

jobs:
  check:
    name: Run Validation Checks
    runs-on: ubuntu-latest

    steps:
      - name: Validate Head Ref
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
          EXPECTED: "main"
        if: ${{ env.HEAD_REF != env.EXPECTED }}
        run: |
          echo
          echo Invalid head ref!
          echo PRs targeting the release branch must have head ref: \'$EXPECTED\'
          echo Current head ref: \'$GITHUB_HEAD_REF\'
          exit 1

      - name: Validate Title
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
          EXPECTED: "chore: kickoff release"
        if: ${{ env.TITLE != env.EXPECTED }}
        run: |
          echo
          echo Invalid title!
          echo PRs targeting the release branch must have the title: \'$EXPECTED\'
          echo Current title: \'$TITLE\'
          exit 1
      
      - name: Validate Actor 
        shell: bash
        env:
          ACTOR: ${{ github.actor }}
          EXPECTED: "testing"
        if: ${{ env.ACTOR != env.EXPECTED }}
        run: |
          echo
          echo Invalid actor!
          echo PRs targeting the release branch must have the actor: \'$EXPECTED\'
          echo Current actor: \'$ACTOR\'
          exit 1
