name: Fastlane

on:
  workflow_call:
    inputs:
      lane:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Fastlane 
    environment: Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up ruby env
        uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: CocoaPods Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: ~/Library/Caches/CocoaPods
          key: pods-release-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
              pods-release-
              pods-Amplify.xcworkspace-
    
      - name: fastlane ios ${{ inputs.lane }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: bundle exec fastlane ios ${{ inputs.lane }}
