# Pushes main to release branch to kick-off the CircleCI release workflow
name: Release Amplify iOS 

on:
  push:
    branches: 
      - chore/gha-release-kickoff # remove this after testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      # - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      #   with:
      #     persist-credentials: true
      #     fetch-depth: 0

      - name: Push main to release branch
        run: git push origin origin/main:ameter/test-release # will change to release after testing
