# Creates a PR to push main to release branch to kick-off the CircleCI release workflow
name: Release Amplify iOS 

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Create PR to push main to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "gh pr create --repo ameter/github-actions-test --title 'chore: kickoff release' --body 'kickoff release' --head main --base release"
