name: UnitTest
on: 
  pull_request: 
    branches:      
      - main      
      - dev-preview

runs-on: macos-12

permissions:
    contents: read 

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  amplify-unit-test:
    environment: UnitTest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: Amplify

  api-unit-test:
    environment: UnitTest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSAPIPlugin  

  auth-unit-test:
    environment: UnitTest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSCognitoAuthPlugin

  datastore-unit-test:
    environment: UnitTest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSDataStorePlugin
  
  storage-unit-test:
    environment: UnitTest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit test
        uses: ./.github/composite_actions/run_xcodebuild_test
        with:
          scheme: AWSS3StoragePlugin  
    
